cut -f2 Orignial_outputs/17_1_2017_S3.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A1_cazy.txt
cut -f2 Orignial_outputs/18_1_2017_S4.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A2_cazy.txt
cut -f2 Orignial_outputs/19_1_2017_S5.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A3_cazy.txt
cut -f2 Orignial_outputs/20_1_2017_S6.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A4_cazy.txt
cut -f2 Orignial_outputs/21_1_2017_S7.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A5_cazy.txt
cut -f2 Orignial_outputs/31_1_2017_S8.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A7_cazy.txt
cut -f2 Orignial_outputs/32_1_2017_S9.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A8_cazy.txt
cut -f2 Orignial_outputs/33_1_2017_S10.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A9_cazy.txt
cut -f2 Orignial_outputs/3_ZOZ_S1.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A6_cazy.txt
cut -f2 Orignial_outputs/4_TEA_S2.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A10_cazy.txt
cut -f2 Orignial_outputs/AARALI_Bulindi_S45.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A11_cazy.txt
cut -f2 Orignial_outputs/Adamou_13_4_2016_Human_S16.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A12_cazy.txt
cut -f2 Orignial_outputs/BaKaaNgombi_27_4_2016_Human_S12.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A13_cazy.txt
cut -f2 Orignial_outputs/Bantu_Agale_Janette_S29.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A14_cazy.txt
cut -f2 Orignial_outputs/Bantu_Aichatau_S33.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A15_cazy.txt
cut -f2 Orignial_outputs/Bantu_Boniuli_S32.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A16_cazy.txt
cut -f2 Orignial_outputs/Bantu_Dicky_Pascale_S42.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A17_cazy.txt
cut -f2 Orignial_outputs/Bantu_Fio_Michael_S35.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A18_cazy.txt
cut -f2 Orignial_outputs/Bantu_Legrand_S27.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A19_cazy.txt
cut -f2 Orignial_outputs/Bantu_Metombo_Modeste_S30.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A20_cazy.txt
cut -f2 Orignial_outputs/Bantu_Mokambi_Seraphine_S28.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A21_cazy.txt
cut -f2 Orignial_outputs/Bantu_Nadege_S31.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A22_cazy.txt
cut -f2 Orignial_outputs/Bantu_Sorozo_Jule_S36.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A23_cazy.txt
cut -f2 Orignial_outputs/Bantu_Vincent_S34.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A24_cazy.txt
cut -f2 Orignial_outputs/Duma_1_4_5_2016_S24.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A25_cazy.txt
cut -f2 Orignial_outputs/GEORGIA_Bulindi_S37.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A26_cazy.txt
cut -f2 Orignial_outputs/GERALD_Bulindi_S41.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A27_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Lungu_1_1_4_5_2016_S18.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A28_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Lungu_2_1_4_5_2016_S52.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A29_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Mapoki_1_2_5_2016_S19.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A30_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Mapoki_1_7_5_2016_S22.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A31_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Mayele_29_4_2016_S21.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A32_cazy.txt
cut -f2 Orignial_outputs/Gorilla_Wiya_1_2_5_2016_S23.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A33_cazy.txt
cut -f2 Orignial_outputs/Ito_15_4_2016_Human_S14.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A34_cazy.txt
cut -f2 Orignial_outputs/JACK_Bulindi_S44.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A35_cazy.txt
cut -f2 Orignial_outputs/JEMIMA_Bulindi_S38.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A36_cazy.txt
cut -f2 Orignial_outputs/JENNY_Bulindi_S40.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A37_cazy.txt
cut -f2 Orignial_outputs/JOYCE_Bulindi_S57.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A38_cazy.txt
cut -f2 Orignial_outputs/Judy_Chimp_Tissue_Zoo_3-7-2017_S50.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A39_cazy.txt
cut -f2 Orignial_outputs/Judy_Chimp_Zoo_3-7-2017_S26.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A40_cazy.txt
cut -f2 Orignial_outputs/KASATU_Bulindi_S43.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A41_cazy.txt
cut -f2 Orignial_outputs/LEILA_Bulindi_S56.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A42_cazy.txt
cut -f2 Orignial_outputs/MERRICK_Bulindi_S39.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A44_cazy.txt
cut -f2 Orignial_outputs/MIRINDA_Bulindi_S59.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A45_cazy.txt
cut -f2 Orignial_outputs/MOSES_Bulindi_S46.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A49_cazy.txt
cut -f2 Orignial_outputs/MURRY_Bulindi_S60.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A50_cazy.txt
cut -f2 Orignial_outputs/Manoi_13_4_2016_Human_S15.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A43_cazy.txt
cut -f2 Orignial_outputs/Molongo_27_4_2016_Human_S13.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A46_cazy.txt
cut -f2 Orignial_outputs/Molube_27_4_2016_Human_S11.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A47_cazy.txt
cut -f2 Orignial_outputs/Mongali_1_7_5_2016_S20.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A48_cazy.txt
cut -f2 Orignial_outputs/OB_Chimp_Fecal_Hodinin_3-7-2017_S25.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A51_cazy.txt
cut -f2 Orignial_outputs/OB_Chimp_Tissue_Hodinin_3-7-2017_S48.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A52_cazy.txt
cut -f2 Orignial_outputs/ROHEN_Bulindi_S47.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A53_cazy.txt
cut -f2 Orignial_outputs/SYLVESTER_Bulindi_S58.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A56_cazy.txt
cut -f2 Orignial_outputs/Sopo_1_1_20_3_2016_S54.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A54_cazy.txt
cut -f2 Orignial_outputs/Susa_1_4_5_2016_S17.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A55_cazy.txt
cut -f2 Orignial_outputs/TEDDY_Bulindi_S55.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A58_cazy.txt
cut -f2 Orignial_outputs/Tea_Chimp_Tissue_Hodinin_3-7-2017_S49.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A57_cazy.txt
cut -f2 Orignial_outputs/Tembo_1_1_21_4_2016_S53.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A59_cazy.txt
cut -f2 Orignial_outputs/Zos_Chimp_Tissue_Hodinin_3-7-2017_S51.CAZy.daa.annotated.besthit | cut -d"|" -f1 |  sort | uniq -c | sed "s/^[ \t]*//" | perl -p -e 's/ /\t/g' > A60_cazy.txt
  
